### ISSUE TITLE
Clarify what should be in quiver.async vs quiver.streams

### ISSUE THREAD

**Issue by justinfagnani** [google/quiver-dart#177]
quiver.streams was supposed to be a `Stream` equivalent of quiver.iterables, but it has things with no equivalent and/or that don't work on a Stream or collection of Streams (like how quiver.iterables works on ... `Iterables`) like `collect` and `StreamBuffer`. It's possible we want to move those to quiver.async.

**Comment by jtmcdole** [comment]
Is async the swiss army knife of quiver (all the tools go there)?  If I were looking for `StreamBuffer`, my first stop would be quiver/streams

**Comment by cbracken** [comment]
I wonder whether we shouldn't just merge everything down to `quiver.async`. `dart:core` doesn't make this distinction, why should we? The other day I was looking for `FutureStream` in `streams` only to discover we'd put it in `async`. I don't see the justification for both.

**Comment by jtmcdole** [comment]
I wish github had a +1 button for an idividual comment, so :+1: to @cbracken

**Comment by justinfagnani** [comment]
Another option is to move everything to package: async once it's on github.

**Comment by sethladd** [comment]
+1 for separate packages, all co-branded Quiver.

**Comment by cbracken** [comment]
Going once, going twice: are we all agreed on merging streams/async libraries?

**Comment by yjbanov** [comment]
+1 to merge them and after 1.0.0 make it a separate package + quiver re-export.

**Comment by justinfagnani** [comment]
I have another thought here: merge `streams` and `iterables` and complete the streams versions.

**Comment by yjbanov** [comment]
@justinfagnani could you please explain why you think it makes sense to merge `streams` and `iterables`, and how you propose to deal with namesake functions, e.g. `collect`?

I agree that we should complete `streams` but I don't think we should block 1.0.0 because of missing features. We can add them in minor releases w/o breaking changes.

**Comment by seaneagan** [comment]
+1 to moving all async stuff over to package:async (or a separate `quiver_async` lib is fine).  I'm running into a lot of dependency conflicts trying to pull in all of quiver.

**Comment by cbracken** [comment]
-1 to merging `streams` and `iterables`; +1 to completing `streams` so that they're as consistent as possible. Personally, I think consistency with the core library split between async/iterables is less surprising than grouping streams/iterables together because of similarities -- but I definitely see value in making them as consistent as possible.

**Comment by justinfagnani** [comment]
So both merging `streams` into `async`, _and_ completing the `streams` library correspondence with `iterables` would mean that a portion of `async` could be documented as "implements `iterables`, but for Streams", while the other part of `async` is "various async utilities", and we'd probably want the docs for `iterables` to point out that there are async versions in `async.

I think it makes a lot more conceptual sense to have a standalone library that focuses on functional transforms of Iterables/Streams. It's easier to document and discover at the very least, probably easier to develop and test if we require the symmetry.

**Comment by yjbanov** [comment]
The similarity between the two is very limited if you can't (Liskov-)substitute one for another. IOW this similarity is not technically applicable. So while it's useful to be able to explain streams via iterables analogy to a new user, I think it should not influence the design of libraries in any way.

Plus, Streams could have a lot of utilities that deal with time and errors, none of which apply to iterables.
