### ISSUE TITLE
Multimaps could also define a []= operator

### ISSUE THREAD

**Issue by BlackHC** [google/quiver-dart#184]
[]= would take an iterable and would essentially perform: 

```
operator []=(K key,Iterable<V> iterable) => this[key]..clear()..addAll(iterable);
```

This would make it easier to operate on multimaps (given the current [] operator).

**Comment by justinfagnani** [comment]
@BlackHC do you have a use case for this feature? Maybe there's another approach that still has consistent behavior, or a variant of the collection that you could opt into.

**Comment by BlackHC** [comment]
To be honest, I'm not sure I can follow the issue. It should be possible to write []= in such a way that x stays consistent.
`mmap['k1'] = x` is hard to interpret because my suggested implementation would break because it would clear x's _delegate. However, 

```
operator []=(K key,Iterable<V> iterable) {
  var safeIterable = iterable.toList(growable: false);
  this[key]..clear()..addAll(safeIterable);
}
```

should work correctly: x would remain the same and synced and any other `y = mmap['k1'];` before that would also be kept in sync.

PS: My use case is wanting to replace all elements for a key with the contents of another iterable.
