### ISSUE TITLE
Multimap.toMap() should be Multimap.asMap() since it returns a live view

### ISSUE THREAD

**Issue by cbracken** [google/quiver-dart#195]
For consistency with SDK naming conventions, `asX` should be used when returning views and `toX` when returning a copy.

Proposed update path:
- add `asMap` and mark `toMap` deprecated with a minor version bump.
- remove `toMap` in the next major version bump.

**Comment by justinfagnani** [comment]
I think we should take a Python-like deprecation policy: deprecate `toMap` in the next "major" version, remove it in the one after that.

**Comment by cbracken** [comment]
Fixed by #227
