### ISSUE TITLE
Consider deprecating/removing glob - refer folks to glob package

### ISSUE THREAD

**Issue by kevmoo** [google/quiver-dart#207]
https://github.com/dart-lang/glob

Focus on what quiver does best?

**Comment by cbracken** [comment]
Agreed - I think this makes sense.

**Comment by justinfagnani** [comment]
Agreed, though Quiver's glob predates the glob package :)

**Comment by justinfagnani** [comment]
I just looked at package:gob and it imports dart:io, so it's not a replacement for this. If that flaw is fixed in package:glob, then I think we could remove it here.

**Comment by justinfagnani** [comment]
Also, a quick micro-benchmark shows that Quiver's Glob is ~4000x faster than package:glob. I don't fully trust that, of course, but it's something to look into.

**Comment by yjbanov** [comment]
Won't fix. See #232
