### ISSUE TITLE
Consider merging iterables into collection library

### ISSUE THREAD

**Issue by cbracken** [google/quiver-dart#239]
In a similar vein to #177, what are people's thoughts for and against merging collections and iterables?

**Comment by yjbanov** [comment]
-1. `iterables` package provides utilities compatible with `dart:core` collections. `collection` is about extending `dart:core` with incompatible new kinds of collections, such as `Multimap`. One effect this has is that utilities in the `iterables` package are not compatible with some of the stuff in `collection`.

**Comment by cbracken** [comment]
Awesome - totally agreed.

**Comment by justinfagnani** [comment]
`iterables` was modeled somewhat of of Python's itertools. I think it could become a standalone package. `collection` could merge into `package:collection`.
