### ISSUE TITLE
Feature request: [fake async] add public getters to get the numbers of pending timers

### ISSUE THREAD

**Issue by vicb** [google/quiver-dart#248]
In Angular, we want to assert that no active timers are queued at the end of a fake async tests.

It would be great to add public getters for that:
- `FakeAsync.pendingTimers`
- `FakeAsync.pendingPeriodicTimers`

**Comment by seaneagan** [comment]
I filed a [similar request](https://github.com/seaneagan/fake_async/issues/8) for the [fake_async](http://pub.dartlang.org/packages/fake_async) package (in case you're interested in using that).

**Comment by vicb** [comment]
@seaneagan thanks for the link.

Some of the Angular customers are already using quiver. I'll probably stick with it.

I'll try to PR something tomorrow if this don't get magically fixed during the night. Should be easy to port to fake_async.

**Comment by vicb** [comment]
Actually @seaneagan could you tell me more about the history of quiver vs fake async (just curious) ?

**Comment by seaneagan** [comment]
@vicb see #169

**Comment by vicb** [comment]
@matanlurey @yjbanov Could you please review the PR ?

**Comment by vicb** [comment]
@seaneagan Shoud I submit a PR to fake_async ?

**Comment by matanlurey** [comment]
We do not use fake_async internally, only quiver, so that part is up to you Vic.

**Comment by seaneagan** [comment]
@vicb up to you, but I would gladly accept it, thanks!
