### ISSUE TITLE
Add a canonical Proxy class

### ISSUE THREAD

**Issue by BlackHC** [google/quiver-dart#249]
```
import 'dart:mirrors';

class Proxy {
  final InstanceMirror _instanceMirror;

  Proxy(instance) : _instanceMirror = reflect(instance);

  dynamic noSuchMethod(Invocation invocation) =>
      _instanceMirror.delegate(invocation);
}
```

Using this, one could write a proxy object simply by using :

```
class MyClassProxy extends Proxy implements MyClass {
  MyClassProxy() : super(new MyClass());
}
```

I can contribute a PR if desired.

**Comment by cbracken** [comment]
Given the general trend toward Mirrors elimination, I'm tempted to close this out. For those who desperately want a proxy (as opposed to using a delegate by composition) it's not a huge amount of boilerplate to write your base class, annotate with `@proxy` and add the overrides they want.

**Comment by cbracken** [comment]
@yjbanov thoughts?

**Comment by cbracken** [comment]
Given the general decision to avoid mirrors in both the internal codebase and most external projects (Flutter, AngularDart), I'm closing this.
