### ISSUE TITLE
Cache will make multiple requests for same key 

### ISSUE THREAD

**Issue by hangstrap** [google/quiver-dart#255]
Assume that the isAbsent function return a future. 
A call is make to access key "foo", this results in a cache miss and isAbsend it called. 
Before isAbsent returns another call is made it access key "foo", and once more isAbsent is called.

This is a bug as  isAbsent has been called twice for the same key. The second call should be 'blocked' until the first isAbsent returns.

```
  test( "test", () async{

    int count=0;
    Future<String> loader (String key){
      count ++;
      print( "inside");
      return new Future.delayed( new Duration( seconds:1), ()=>"Test");
    }

    MapCache<String, String> cache = new MapCache.lru();
    FutureGroup f = new FutureGroup();
    f.add( cache.get( "test", ifAbsent:loader));
    f.add( cache.get( "test", ifAbsent:loader));

    await f;
    expect( count, equals(1));
  });
```

**Comment by matanlurey** [comment]
@cbracken could you assign this to me? I'm observing the same bug internally, will fix this week.

**Comment by adamlofts** [comment]
Do you have an internal fix you can pick and apply to this? If not this is a bug I would like to fix can can work on next week.
