### ISSUE TITLE
Ergonomic API for isolating tests written for package:test

### ISSUE THREAD

**Issue by yjbanov** [google/quiver-dart#262]
## Problem

`package:test` no longer provides a good way to isolate tests right from the test code itself (https://github.com/dart-lang/test/issues/127)
## Proposal
- Add new library `package:quiver/testing/unit.dart`, which has
  - `itest` - isolates one test
  - `igroup` - isolates a group of tests
- The library also reexports `package:test/test.dart` so that
  - users only need to import one thing
  - it serves as a drop-in replacement for the underlying package

**Comment by zoechi** [comment]
I don't think it's a good idea to add this to quiver. `test` adds a lot of dependencies (like shelf, polymer, ... https://github.com/dart-lang/test/blob/master/pubspec.yaml) and if you want to use quiver as normal dependency (not dev_dependency) you add all these dependencies to your package and all users of your package. I think there should be a new package created for this purpose.

**Comment by justinfagnani** [comment]
I agree, this doesn't seem like something to add to Quiver. From the issue on `test` it sounds like enabling a more opinionated runner based on tags, and/or wrapping `test` is one of their design goals, so it would be perfectly inline with that to start that as it's own package.

**Comment by yjbanov** [comment]
@zoechi I'm not yet sure if it's possible, but if we can keep `package:test` a `dev_dependency` of quiver, then you wouldn't automatically pull in `package:test` with `pub get` if you depend on quiver.

@justinfagnani We already plan making `package:quiver/testing` its own package. I don't think it matters if we add these utilities before or after the split.

Note that this proposal does not include a new test runner, only a handful of useful functions. You would still use normal `pub run test` to run your tests.

**Comment by zoechi** [comment]
@yjbanov I guess not. If it is a dev_dependency it is only available for development of quiver (test/*, tool/*, example/*) and must not be used in code in lib/*. and therefore isn't available to packages depending on quiver.

**Comment by cbracken** [comment]
Closing this out as we have no plans to implement this in quiver.
