### ISSUE TITLE
Optional<T> should implement Iterable<T>

### ISSUE THREAD

**Issue by akuzyakov** [google/quiver-dart#266]
It will allow trivial flattening of `Iterable<Optional<T>>` (just call concat).
Related to this issue: https://github.com/google/quiver-dart/issues/76

**Comment by justinfagnani** [comment]
I don't think this would be a great solution to #76 since concat would end up creating an iterator instance per item, where as the `wherePresent` pattern mentioned there wouldn't create any extra objects.

**Comment by cbracken** [comment]
Not planned.

**Comment by whesse** [comment]
It says in the documentation that Optional now implements Iterable.  Could this bug be updated with this change to the decision, and information on any limitations of Optional's implementation of Iterable?

**Comment by yjbanov** [comment]
@whesse good point. This was implemented.
