### ISSUE TITLE
Make checkNotNull (and friends) generic for strong-mode

### ISSUE THREAD

**Issue by ochafik** [google/quiver-dart#286]
Related to #285, but this is to help user code that looks like `doSomething(checkNotNull(someArg))`.

Note that [strong-mode](https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md) comes with generic methods with syntax `/*=T*/ checkNotNull/*<T>*/(/*=T*/ value)`.

**Comment by ochafik** [comment]
cc/ @emesx

**Comment by emesx** [comment]
On it, ETA Monday.

**Comment by cbracken** [comment]
Fixed by #290
