### ISSUE TITLE
Breaking change needing fix and/or version bump: deletion of streams.dart

### ISSUE THREAD

**Issue by ochafik** [google/quiver-dart#294]
671f1bc75742b4393e203c9520a3bf1e031967dc deleted `lib/streams.dart`, which is a breaking change.

I'd suggest reintroducing this file with reexports for the next minor release (with strong-mode fixes, etc), then delete it again after the next major version bump.

**Comment by cbracken** [comment]
IIRC this was deleted between 0.21.0 and 0.22.0. A +0.1.0 version bump signifies a backwards-incompatible change under Dart's variant of semver, for pre-1.0.0 packages.

Whether Quiver should be pre-1.0.0 at this point is a separate question altogether ;)
