### ISSUE TITLE
feature request: indexed set

### ISSUE THREAD

**Issue by pschiffmann** [google/quiver-dart#300]
An indexed set is a set -- "a collection of objects in which each object can occur only once" [1](https://api.dartlang.org/stable/1.18.1/dart-core/Set-class.html) -- that uses a custom hash function, and exposes the hash/object relation in its public API:

``` Dart
abstract class IndexedSet<K, V> implements Set<V> {
  IndexedSet(K hash(V v));

  V operator [](K key);
  bool containsKey(K key);
}
```

use case: I occasionally have a collection of objects, in which I want to look up single objects by some key; finding a user by its username, an invoice by its id, or a variable by its name (in a language interpreter).
A simple approach is to store all users/invoices/variables in a Map:

``` Dart
var dummy = new User('pschiffmann');
...
Map<String, User> users = {dummy.name: dummy};
print(users['pschiffmann']);
```

But from a conceptual point of view, `users` is not a Map. This is slightly inconvenient when the map object is purely internal -- creating the relation `users[user.name] = user;` by hand feels unclean, but if I only need to write it in a single method, I can tolerate it.
It is however a bigger problem when I accept a collection of users as a function parameter: Do I specify the function parameter as `Iterable<User>` and create the according Map internally, again and again, in every function that needs to look up users; or do I trust the caller passes me a well-formed map?

Because the intention behind Map never was to be used for this scenario anyways, I'd prefer this way instead:

``` Dart
var users = new IndexedSet<String, User>((User user) => user.name);
users.add(dummy);
print(users['pschiffmann']);
```

---

I don't know if there is an established name for this data structure; _IndexedSet_ is what came to my mind ...

I will gladly implement it and file a pull request -- I just wanted to check first if there is interest at all. :-)

Best regards
Philipp

**Comment by jtmcdole** [comment]
Isn't that just [Map.fromIterable](https://api.dartlang.org/stable/1.18.1/dart-core/Map/Map.fromIterable.html)
```dart
main() {
  var input = [new User('joe'), new User('bob'), new User('bob')];
  var users = new Map.fromIterable(input, key: (e) => e.name);
  print(users);
  print(users['bob']);
}

class User {
  final String name;
  User(this.name);
  String toString() => "User($name)";
}
```

**Comment by pschiffmann** [comment]
> Isn't that just Map.fromIterable

Sure, I _can_ use a`Map<String, User>` and dictate in the docs that there exists some function _f: User -> String_, that must be used to compute the key for each value. I think this approach is inferior to an explicit class because

1. The map can't enforce or validate that a key actually belongs to its value. `users['bob'] = new User('joe')` passes silently.
2. It's not in the scope of an application to enforce integrity between keys and values; this is a task for the data structure.  
If I need a _collection of unique elements_, I can obviously create one using a `List` and check for duplicates before modification -- but now I just mimic a `LinkedSet`. When you e.g. take a look at my user management source code to read up on some implementation details, you'll prefer the latter option, because you want to read about how user management works, not how Sets work.  
The same applies here: while it is an obvious choice to implement an IndexedSet using a Map, the implementation detail doesn't matter for an application that uses IndexedSets.
3. I want self-explaining code (haha, don't we all), and in my experience distinctive types help a lot. When you use my function `Set<User> getUsers()`, you can derive some valuable knowledge from the return type alone: for example, you know you won't find any duplicates in there.  
Now, when I ask you to pass me a `Map` as a function parameter, you derive from the type: "this is a collection where you can associate a value with one or more keys". Then you look up the functions doc comment, where I write "keys _must_ be in coherence with their values, and values must be unique". By using a data structure that is inappropriate for my use case, I give you two rivaling preconditions that contradict each other -- given you look at my documentation at all.
4. You can't add a new element to the map without the function that computes the keys. You can't efficiently look up elements either (`users.values.contains()` works, but surely isn't ideal). So passing around a map of users implies passing the function as a separate value as well, despite the fact that they form a conceptual union, and neither is useful without the other.

**Comment by pschiffmann** [comment]
Sorry for opening this rather obscure issue and then never responding to it ...
I had originally intended to implement this myself and send you a pull request, but then never got around to finish it. Anyways, I have implemented it [here](https://github.com/pschiffmann/indexed-set.dart) now and will publish it shortly on pub. Don't ask my why I didn't just do that a year ago. ¯\_(ツ)_/¯

Best regards,
Philipp

**Comment by cbracken** [comment]
@pschiffmann Nice! Thanks for updating the bug with the info.
