### ISSUE TITLE
String indent?

### ISSUE THREAD

**Issue by xster** [google/quiver-dart#351]
`=> input.split('\n').map((String line) => ' ' * indentAmount + line).join('\n')`
or something in one simple method?

**Comment by jtmcdole** [comment]
1. + is generally not used for String.
2. Use LineSplitter
3. Would this work?
```dart
  int amount = 2;
  for (var line in ["foo", "bar", "baz"]) {
    print("${'  ' * amount}$line");
  }
```

```shell
    foo
    bar
    baz
```

**Comment by lrhn** [comment]
You can use `line.padLeft(amount)` to left-pad `line` with `amount` spaces.
