### ISSUE TITLE
Efficient conversion from Iterable to sorted collection

### ISSUE THREAD

**Issue by patkujawa-wf** [google/quiver-dart#352]
It's not uncommon to see code that turns an iterable into a list just to call `.sort` on that list. I'm not sure, but I assume that that causes memory duplication as well as not being as fast as some alternatives. For example, an API for inserting in sort order, assuming the underlying collection is already sorted.

I couldn't find any such feature in Dart or quiver or requests for it, but please close and link to them if they already exist. Thanks!

**Comment by patkujawa-wf** [comment]
Ah, it looks like [SplayTreeSet class - dart:collection library - Dart API](https://api.dartlang.org/stable/1.23.0/dart-collection/SplayTreeSet-class.html) works as long as you're just iterating and don't need index access.

I was clued in by [Set class - dart:core library - Dart API](https://api.dartlang.org/stable/1.23.0/dart-core/Set-class.html) docs:
> Iterating over elements of a set may be either unordered or ordered in some way. Examples:

> A HashSet is unordered, which means that its iteration order is unspecified,
> LinkedHashSet iterates in the insertion order of its elements, and
> a sorted set like SplayTreeSet iterates the elements in sorted order.

Here's a [demo](https://dartpad.dartlang.org/a4739139b2def328fa51c3c92fd93167)

Anyone know other limitations to this route, or things I've misunderstood about it?

**Comment by lrhn** [comment]
There is no better way to sort unsorted data than to make it a list (if it isn't already) and then sort the list.

The `SplayTreeSet` is a data structure that *maintains* data in sorted order, which avoids the need to sort it later. That's a perfectly good solution if you can work with your data in a `Set`, you just need to know up-front that that is the case - and obviously your data needs to have an ordering. Apart from that, there shouldn't be any limitations.
