### ISSUE TITLE
Consider making _daysInMonth and _isLeapYear public

### ISSUE THREAD

**Issue by jolleekin** [google/quiver-dart#378]
When creating a date picker Polymer element, a date picker Angular component, or a subscription management system, developers will likely need `_daysInMonth` and `_isLeapYear`. If these two functions are made public, developers only need to import this package instead of defining their own.

**Comment by cbracken** [comment]
Seems like totally reasonable things for Quiver to expose. I can imagine that long term, we might want to expose a clean set of time APIs, but we can always expose these as top-level functions, then if we ever get around to building something better, add the new APIs and deprecate these ones.

@yjbanov @a14n thoughts?

**Comment by cbracken** [comment]
Landed in #381, will be released in v0.26.0, in #382.

**Comment by cbracken** [comment]
And 0.26.0 is released on pub! @jolleekin Thanks for suggesting this!
