### ISSUE TITLE
#265 is not documented in CHANGELOG.md

### ISSUE THREAD

**Issue by matanlurey** [google/quiver-dart#400]
I'm fairly sure https://github.com/google/quiver-dart/pull/265 will not pass Google.

This should either be reverted, or we need a volunteer to land this change.

**Comment by cbracken** [comment]
The fact that this change was not documented in the changelog is an error on my part. I'll get that fixed.

That said, this is not a breaking change -- or I should say, by this definition of breaking change, every bugfix or change is a breaking change. If people are relying on a bug in Quiver's implementation of timer ordering, which previously made it inconsistent with actual execution, their code contains a bug and should be fixed -- arguably a bug that was quiver's fault in the first place.

**Comment by cbracken** [comment]
Actually, looking at the changelog, #265 *was* documented in the changelog under v0.27.0 as a fix in the commit that landed the change.
