### ISSUE TITLE
Slow down breaking releases?

### ISSUE THREAD

**Issue by kevmoo** [google/quiver-dart#411]
Quiver is big and it's used a little bit by a lot of packages.

Handling each update is a pain across a lot of packages.

Could we slow them down a bit? Chunk breaks into bigger, but less frequent updates?

CC @cbracken

**Comment by cbracken** [comment]
Do you have specific examples? @matanlurey filed some issues recently, but all PRs since then have come from Dart team members working within Google.

**Comment by kevmoo** [comment]
Just that quiver has had two "major" (breaking) releases in just over 2
weeks - https://pub.dartlang.org/packages/quiver#-changelog-tab-

**Comment by cbracken** [comment]
Both of those were PRs submitted by Dart team members, and both releases were pushed for ASAP. @srawlins can provide more info.

I’d be glad to adopt some sort of official release schedule but it’s not possible to adopt one with conflicting requirements. Fortunately most of these PRs are comin from the Dart team, so should be easy to sort out something agreeable. Answers to the above questions would provide a great basis for a discussion on this.

**Comment by srawlins** [comment]
@kevmoo both of those releases were high priority for Dart 2.0, to allow breaking changes to land for Iterable and friends. The Dart 2.0 Iterable changes were blocked until all packages in DEPS had stub implementations for new Iterable methods.

What release numbering / cadence would you suggest?

**Comment by kevmoo** [comment]
Needed for Dart 2: totally fine!

It just quiver has become like path and collection – used deeply
everywhere. It takes a while to update enough things for packages to catch
up.

Just something to be aware of.

Thanks!

**Comment by cbracken** [comment]
Anything further we should do here in terms of changes to the release process/frequency? I think it’s totally reasonable to do so and not something we’ve consciously sat down and done in a while. Any input on the questions above would help with that, if we want to do so.

**Comment by srawlins** [comment]
Hopefully there are no more breaking-for-dart-2 changes, but we may be misinformed, we'll see.

In general, what about releasing -dev releases? There can be breaking changes between 0.29.0-dev.1 and 0.29.0-dev.2. Mockito and Markdown are in this state now, and I find it really comforting, while they're under active development, that we can play around a lot, make breaking changes, and not worry about have just released a breaking-change release.

**Comment by kevmoo** [comment]
SGTM
