### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [google/quiver-dart#456]
When running tests in Dart 2 mode, see failures 

 type 'List<int>' is not a subtype of type 'List<List<int>>' in type cast where
    List is from dart:core
    int is from dart:core
    List is from dart:core
    List is from dart:core
    int is from dart:core
  
  dart:core                                                                            Object._as
  ../..quiver/lib/src/async/stream_buffer.dart 93:20    StreamBuffer._consume
  ../..quiver/lib/src/async/stream_buffer.dart 147:36   StreamBuffer.addStream.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                           _StreamImpl.listen
  ../..quiver/lib/src/async/stream_buffer.dart 138:19   StreamBuffer.addStream
  dart:async                                                                           Stream.pipe
  .././quiver/test/async/stream_buffer_test.dart 29:10  main.<fn>.<fn>

**Comment by cbracken** [comment]
This sounds like the sort of errors you might get from building something in Dart 1 and running in Dart 2 mode. Can you provide repro instructions?

**Comment by keertip** [comment]
dart --preview-dart-2 test/async/stream_buffer_test.dart

**Comment by cbracken** [comment]
These are all resolved.
