### ISSUE TITLE
StreamBuffer needs to implement StreamConsumer<List<T>>

### ISSUE THREAD

**Issue by jtmcdole** [google/quiver-dart#457]
I've mentioned this before, and I don't remember why we landed on StreamConsumer<T>. In every case that I can remember using StreamBuffer, it was with a socket.

Thoughts on changing this to List<T>?

https://github.com/google/quiver-dart/blob/747f91d82a6a9e25d75d87c737faf2d937e4ece0/lib/src/async/stream_buffer.dart#L45

**Comment by srawlins** [comment]
I think switching to implement `StreamConsumer<List<T>>` would solve #456 .

**Comment by cbracken** [comment]
Fixed by #467.
