### ISSUE TITLE
MapCache: Can't clear a failed Future

### ISSUE THREAD

**Issue by creisman** [google/quiver-dart#461]
https://github.com/google/quiver-dart/blob/98dd92f4fd89fb8262a557db259e3bba7fde18cb/lib/src/cache/map_cache.dart

The value gets added to _outstanding, then is awaited. If the await throws an exception, it gets kicked out of the method and never clears the key from _outstanding. Subsequent calls will always return the failed Future. There's no way to evict a key from the _outstanding map so it's permanently broken for that key.

The [await](https://github.com/google/quiver-dart/blob/98dd92f4fd89fb8262a557db259e3bba7fde18cb/lib/src/cache/map_cache.dart#L44) either needs to be in a try/finally that removes it from _outstanding or invalidate needs to also try and remove keys from _outstanding.

**Comment by creisman** [comment]
@adamlofts

**Comment by yjbanov** [comment]
Fixed in https://github.com/google/quiver-dart/commit/252d1c71ac171d9044f145a301d19749b1cabba1
