### ISSUE TITLE
Add Optional.isNotPresent to quiver.core

### ISSUE THREAD

**Issue by kostaa** [google/quiver-dart#482]
Would it be possible to add `Optional.isNotPresent` getter? I find myself using the `false == opt.isPresent` far more often then `opt.isPresent`.

**Comment by yjbanov** [comment]
What do you think of `!opt.isPresent`?

**Comment by kostaa** [comment]
Yeah that is always possible but tired eyes sometimes miss that slim explanation mark so I prefer to use the more in your face form :-) .

Anyway my suggestion just follows similar patters - eg collections isEmpty/isNotEmpty....

**Comment by zoechi** [comment]
it's like `isNotEmpty`

**Comment by cbracken** [comment]
Seems like a reasonable to me! Sent #483.
