### ISSUE TITLE
Provide isNotBlank

### ISSUE THREAD

**Issue by feinstein** [google/quiver-dart#503]
Since there's `isNotEmpty()`, it would be nice to also have `isNotBlank()`.

**Comment by cbracken** [comment]
Sounds like a good idea to me! More than happy to take a PR if you'd like to send one -- if not, one of us can bang something up.

**Comment by feinstein** [comment]
Ok, I will send one shortly.

**Comment by feinstein** [comment]
I was updating the version on `pubspec.yaml`, should I add my name to the authors list as well?

**Comment by cbracken** [comment]
Absolutely -- please do :)

**Comment by cbracken** [comment]
Thanks for your contribution! This is included in version 2.0.5, which is now published to pub.

**Comment by feinstein** [comment]
I thank you for being so helpful :)
