### ISSUE TITLE
StreamBuffer not working with socket anymore

### ISSUE THREAD

**Issue by hauketoenjes** [google/quiver-dart#596]
Hi, 

In this [commit](https://github.com/dart-lang/sdk/commit/cab2ca275d548e947e5577a49ff3a3302650a2ac#diff-f5f97039d5294a0ce2c5a87d3717eb43) to the dart sdk the socket no longer implements a `Stream<List<int>>` but implements a Stream`<UInt8List>`.

When you try the example code from the [docs](https://pub.dev/documentation/quiver/latest/quiver.async/StreamBuffer-class.html) it gives you an error `Error: The argument type 'StreamBuffer<int>' can't be assigned to the parameter type 'StreamConsumer<Uint8List>`. Is this intended or should the `StreamBuffer` implement StreamConsumer<UInt8List>? That would fix it for sockets but not for any other data then..

**Comment by jtmcdole** [comment]
Thanks for the report. If you read the breaking change notice; you can:
`stream.cast<List<int>>().pipe(consumer)`. We can update the documentation
if we can't find a way to smooth the generics.
