### ISSUE TITLE
TreeSet.first/last appear to be returning the same value (in some cases?)

### ISSUE THREAD

**Issue by cbracken** [google/quiver-dart#674]
Wrote a basic test to repro in (internal) cl/341420723. It looks like TreeSet.first and TreeSet.last are returning the same value. Last passed at CL 340929408. Patch landed to stop using TreeSet.last in cl/341430249.

**Comment by jtmcdole** [comment]
Oooof.  I'll take a look tomorrow.

**Comment by jtmcdole** [comment]
Found it.
