### ISSUE TITLE
migrate Optional<T> -> "T?"

### ISSUE THREAD

**Issue by fzyzcjy** [google/quiver-dart#679]
Hi thanks for the lib! Since now null safety is stable, we want to migrate all `Optional<T>` to `T?`. Can this be done with some tools? Thanks

**Comment by cbracken** [comment]
Unfortunately we don't have any tools to automatically migrate `Optional<T>`s to `T?`. It could be done by using the [analyzer](https://pub.dev/packages/analyzer) package. 

There are a few bits to be careful of. Specifically:
1. The [transform](https://github.com/google/quiver-dart/blob/370a495e37dc10b4c6514a9822574ff5041d389b/lib/src/core/optional.dart#L87-L96) and [transformNullable](https://github.com/google/quiver-dart/blob/370a495e37dc10b4c6514a9822574ff5041d389b/lib/src/core/optional.dart#L98-L107) methods.
2. Dealing with the fact that `Optional<T>` implements `Iterable<T>`. This allows `Optional`s to be elided when used in an iterable context such that, for example `[Optional<int>.of(1), Optional<int>.absent(), Optional<int>.of(2)].expand((i) => i)` results in `[1, 2]`.

If you or anyone else were keen to implement such a thing in a tested way, I think we'd be glad to point people to it in the docs for `Optional`, or add it as a tool under a `bin` directory.

**Comment by SShayashi** [comment]
Are there any new updates?
The latest Flutter 3.10 adopts Dart3 and only allows null safety code to be executed.
Many developers will be looking for a migration tool.

**Comment by fzyzcjy** [comment]
I personally migrated it (2 years ago) using hacky regular expressions...
