### ISSUE TITLE
pub.dev shows "Publisher: unverified uploader"

### ISSUE THREAD

**Issue by jsroest** [google/quiver-dart#691]
The publisher should be 'google.dev'.

Thanks!
Sander

![image](https://user-images.githubusercontent.com/17854207/152156719-cb894a61-8ff9-470d-add7-f7b6e68e56f3.png)

**Comment by cbracken** [comment]
Thanks for filing this -- you're absolutely correct! We first published this when pub only supported email addresses for publishers, but we never fixed this when we added more general publisher support. We'll get this fixed.

**Comment by mit-mit** [comment]
@cbracken I sent you an invite to the google publisher.

**Comment by cbracken** [comment]
This is now fixed. Thanks @mit-mit (and @jsroest for raising the issue!)

**Comment by codegrue** [comment]
What are the steps to fix this? I have the same issue.

**Comment by mit-mit** [comment]
See https://dart.dev/tools/pub/publishing#create-verified-publisher
