### ISSUE TITLE
Dart 3: BidirectionalIterator deprecated

### ISSUE THREAD

**Issue by AlexVegner** [google/quiver-dart#724]
Failed to build iOS app
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
treeset.dart:45

https://api.flutter.dev/flutter/dart-core/BidirectionalIterator-class.html
BidirectionalIterator deprecated and removed from Dart 3

Reproducible with latest fluttre beta: [3.8.0-10.1.pre]

**Comment by cbracken** [comment]
Have you updated to a version >　3.2.0? This was removed in December 2022 in https://github.com/google/quiver-dart/pull/714.
