### ISSUE TITLE
Clock has too many methods

### ISSUE THREAD

**Issue by seaneagan** [google/quiver-dart#92]
If we had #91, then instead of:

``` dart
clock.ago(days: 1)
clock.weeksAgo(2)
clock.yearsFromNow(1)
```

could just do:

``` dart
clock.ago(day)
clock.ago(week * 2)
clock.fromNow(year)
```

though I'd probably be happy with just doing:

``` dart
clock.now().subtract(day)
clock.now().subtract(week * 2)
clock.now().add(year)
```

For months, a special function would still be needed, but it ought to work for any date, not just `now()`:

``` dart
DateTime addMonths(DateTime from, int months);
```

**Comment by cbracken** [comment]
Closing as stale. This class is so heavily used internally that changing these APIs at this point that the benefit outweighs the cost. As mentioned elsewhere, I've always been a fan of `offsetBy(Duration)` or at least `offsetBy({years, weeks, days, ...})` but I'm not sure we'll find many people keen to sign up for the thousands of patches we'd need to land to migrate :-)
